import { EventBudget, ExpenseTransaction, AuditBlock, UserProfile } from '@/types/finance';

export const INITIAL_PROFILES: Record<string, UserProfile> = {
  president: {
    id: 'usr_pres_01',
    email: 'president@pupaccess.org',
    position_title: 'Organization President',
    role: 'PRESIDENT',
    incumbent_name: 'Sophia Lim',
    incumbent_student_no: '2022-01923-MN-0',
    incumbent_term: 'A.Y. 2025-2026',
  },
  treasurer: {
    id: 'usr_treas_01',
    email: 'treasurer@pupaccess.org',
    position_title: 'Finance Officer / Treasurer',
    role: 'FINANCE_OFFICER',
    incumbent_name: 'Daniel Bithao',
    incumbent_student_no: '2023-04821-MN-0',
    incumbent_term: 'A.Y. 2025-2026',
  },
  projectHead: {
    id: 'usr_ph_01',
    email: 'projecthead.hardhatting@pupaccess.org',
    position_title: 'Hardhatting Committee Director',
    role: 'PROJECT_HEAD',
    incumbent_name: 'Ren Zapanta',
    incumbent_student_no: '2023-08291-MN-0',
    incumbent_term: 'A.Y. 2025-2026',
  },
  studentMember: {
    id: 'usr_mem_01',
    email: 'student.member@pup.edu.ph',
    position_title: 'ACCSS General Member',
    role: 'STUDENT_MEMBER',
    incumbent_name: 'Andrei Saldivar',
    incumbent_student_no: '2024-03912-MN-0',
    incumbent_term: 'A.Y. 2025-2026',
  },
};

export const INITIAL_EVENTS: EventBudget[] = [
  {
    id: 'evt_cpe_fair_2025',
    fiscal_year_id: 'fy_2025_2026',
    name: 'CpE Fair Financial Summary',
    slug: 'cpe-fair-summary-2025',
    purpose: 'Inter-year sports tournament, esports, and departmental exhibits. Managed via Quota collections, Bettermind partnership, and ACCESS mother funds.',
    technique: 'ACTIVITY_BASED',
    total_allocated: 48162.16, // Grand Total Funds
    contingency_buffer: 1977.00, // Left from Quota
    spent_amount: 42805.43, // Grand Total Expenses
    status: 'COMPLETED',
    project_head_id: 'usr_ph_01',
    project_head_name: 'Antonio Nickel Tantia / Kuya Allan',
    categories: [
      { id: 'cat_fair_bball', event_budget_id: 'evt_cpe_fair_2025', name: 'Basketball (7 Teams Quota)', allocated_amount: 14880, spent_amount: 14000 },
      { id: 'cat_fair_vball', event_budget_id: 'evt_cpe_fair_2025', name: 'Volleyball (6 Teams Quota)', allocated_amount: 14960, spent_amount: 12439 },
      { id: 'cat_fair_badminton', event_budget_id: 'evt_cpe_fair_2025', name: 'Badminton (5 Teams Quota)', allocated_amount: 2320, spent_amount: 2320 },
      { id: 'cat_fair_esports', event_budget_id: 'evt_cpe_fair_2025', name: 'Esports Tournament (25 Teams)', allocated_amount: 5244, spent_amount: 6080 },
      { id: 'cat_fair_access', event_budget_id: 'evt_cpe_fair_2025', name: 'ACCESS Org Materials & Trophies', allocated_amount: 10758.16, spent_amount: 7966.43 },
    ],
    created_at: '2025-11-15T08:00:00Z',
  },
  {
    id: 'evt_hardhatting_2026',
    fiscal_year_id: 'fy_2025_2026',
    name: 'Coded for the Future: Hardhatting Ceremony 2026',
    slug: 'hardhatting-ceremony-2026',
    purpose: 'Official departmental hardhatting ceremony and rites of passage for 2nd year Computer Engineering students at PUP Bulwagang Balagtas.',
    technique: 'ACTIVITY_BASED',
    total_allocated: 85000,
    contingency_buffer: 8500, // 10% locked safety buffer
    spent_amount: 61250,
    status: 'ACTIVE',
    project_head_id: 'usr_ph_01',
    project_head_name: 'Ren Zapanta',
    categories: [
      { id: 'cat_hh_1', event_budget_id: 'evt_hardhatting_2026', name: 'Hardhat Gear & Safety Collaterals', allocated_amount: 32000, spent_amount: 28400 },
      { id: 'cat_hh_2', event_budget_id: 'evt_hardhatting_2026', name: 'Stage, AV & Bulwagang Balagtas Venue', allocated_amount: 22000, spent_amount: 18500 },
      { id: 'cat_hh_3', event_budget_id: 'evt_hardhatting_2026', name: 'Food & Dignitary Refreshments', allocated_amount: 18000, spent_amount: 14350 },
      { id: 'cat_hh_4', event_budget_id: 'evt_hardhatting_2026', name: 'Certificates & Tokens for Faculty', allocated_amount: 4500, spent_amount: 0 },
      { id: 'cat_hh_5', event_budget_id: 'evt_hardhatting_2026', name: 'Earmarked Contingency (10%)', allocated_amount: 8500, spent_amount: 0 },
    ],
    created_at: '2026-05-15T08:00:00Z',
  },
  {
    id: 'evt_ce_month_2026',
    fiscal_year_id: 'fy_2025_2026',
    name: 'Computer Engineering Month 2026',
    slug: 'ce-month-2026',
    purpose: 'Inter-batch technical competitions, hackathons, robotics exhibits, and esports tournament for over 1,500 CpE students.',
    technique: 'ENVELOPE_70_20_10',
    total_allocated: 120000,
    contingency_buffer: 12000,
    spent_amount: 84500,
    status: 'ACTIVE',
    project_head_name: 'Charlean Broqueza',
    categories: [
      { id: 'cat_ce_1', event_budget_id: 'evt_ce_month_2026', name: 'Hackathon & Technical Equipment', allocated_amount: 45000, spent_amount: 39000 },
      { id: 'cat_ce_2', event_budget_id: 'evt_ce_month_2026', name: 'Prizes, Medals & Trophy Engraving', allocated_amount: 35000, spent_amount: 32000 },
      { id: 'cat_ce_3', event_budget_id: 'evt_ce_month_2026', name: 'Marketing, Banners & Livestream AV', allocated_amount: 15000, spent_amount: 13500 },
      { id: 'cat_ce_4', event_budget_id: 'evt_ce_month_2026', name: 'Guest Speaker Honorarium', allocated_amount: 13000, spent_amount: 0 },
      { id: 'cat_ce_5', event_budget_id: 'evt_ce_month_2026', name: 'Contingency Envelope', allocated_amount: 12000, spent_amount: 0 },
    ],
    created_at: '2026-06-01T08:00:00Z',
  },
  {
    id: 'evt_jao_seminar_2026',
    fiscal_year_id: 'fy_2025_2026',
    name: 'JAO Leadership & Technical Seminar Series',
    slug: 'jao-seminars-2026',
    purpose: 'Foundational organizational systems training and hands-on workshops for Junior ACCESS Officers and subordinates.',
    technique: 'ZERO_BASED',
    total_allocated: 35000,
    contingency_buffer: 3500,
    spent_amount: 22800,
    status: 'ACTIVE',
    project_head_name: 'John Andrei Saldivar',
    categories: [
      { id: 'cat_jao_1', event_budget_id: 'evt_jao_seminar_2026', name: 'Workshop Materials & Handouts', allocated_amount: 12000, spent_amount: 8800 },
      { id: 'cat_jao_2', event_budget_id: 'evt_jao_seminar_2026', name: 'Meals & Refreshments (2 Sessions)', allocated_amount: 16000, spent_amount: 14000 },
      { id: 'cat_jao_3', event_budget_id: 'evt_jao_seminar_2026', name: 'Speaker Plaque & Certificates', allocated_amount: 3500, spent_amount: 0 },
      { id: 'cat_jao_4', event_budget_id: 'evt_jao_seminar_2026', name: 'Emergency Contingency', allocated_amount: 3500, spent_amount: 0 },
    ],
    created_at: '2026-06-20T08:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: ExpenseTransaction[] = [
  {
    id: 'tx_fair_01',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_access',
    category_name: 'ACCESS Org Materials & Trophies',
    tracking_number: 'ACCSS-2025-IN-001',
    title: 'Bettermind Partnership Cash In',
    description: 'Corporate partnership sponsorship funds for CpE Fair ball games & technical seminars.',
    type: 'SPONSORSHIP',
    status: 'CERTIFIED_DISBURSED',
    amount: 3000,
    cash_in: 3000,
    wallet: 'GCASH',
    funding_source: 'PARTNERSHIP_SPONSOR',
    remarks: 'Partnership deposit',
    reimbursement_notes: 'Received via GCash',
    transacted_at: '2025-11-27T10:00:00Z',
    submitted_by_id: 'usr_treas_01',
    submitted_by_name: 'Daniel Bithao',
    approvals: [],
    created_at: '2025-11-27T10:00:00Z',
  },
  {
    id: 'tx_fair_02',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_badminton',
    category_name: 'Badminton (5 Teams Quota)',
    tracking_number: 'ACCSS-2025-EXP-002',
    title: 'Courtzone Inc - Badminton Court Reservation',
    description: 'Badminton court booking payment for CpE Fair games reserved by Kuya Allan.',
    type: 'DISBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 2000,
    wallet: 'GOTYME',
    funding_source: 'QUOTA',
    remarks: 'Badminton Court Reservation by Kuya Allan',
    reimbursement_notes: 'Paid via GoTyme bank transfer',
    transacted_at: '2025-12-09T14:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Kuya Allan',
    approvals: [],
    created_at: '2025-12-09T14:00:00Z',
  },
  {
    id: 'tx_fair_03',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_bball',
    category_name: 'Basketball (7 Teams Quota)',
    tracking_number: 'ACCSS-2025-EXP-003',
    title: 'NDC Court Payment for Basketball Games',
    description: 'NDC Basketball court payment for Dec 10 sent to Antonio Nickel Tantia.',
    type: 'DISBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 4000,
    wallet: 'GOTYME',
    funding_source: 'QUOTA',
    remarks: 'NDC Court Payment for Dec 10 sent to Antonio',
    reimbursement_notes: 'Sent via GoTyme',
    transacted_at: '2025-12-09T15:30:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Antonio Nickel Tantia',
    approvals: [],
    created_at: '2025-12-09T15:30:00Z',
  },
  {
    id: 'tx_fair_04',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_vball',
    category_name: 'Volleyball (6 Teams Quota)',
    tracking_number: 'ACCSS-2025-EXP-004',
    title: 'Valencia Court Payment for Volleyball',
    description: 'Valencia Volleyball court rental for Dec 9, 2025.',
    type: 'DISBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 5000,
    wallet: 'GCASH',
    funding_source: 'QUOTA',
    remarks: 'Valencia Court Payment Dec 9, 2025',
    reimbursement_notes: 'Paid via GCash (Timmy Gregorio)',
    transacted_at: '2025-12-09T16:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Timmy Gregorio',
    approvals: [],
    created_at: '2025-12-09T16:00:00Z',
  },
  {
    id: 'tx_fair_05',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_esports',
    category_name: 'Esports Tournament (25 Teams)',
    tracking_number: 'ACCSS-2025-EXP-005',
    title: 'ESPORTS Prize Pool & Player Water Reimbursement',
    description: 'Prize pool disbursement for winning teams and mineral water bottles for tournament participants.',
    type: 'REIMBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 6080,
    wallet: 'GCASH',
    funding_source: 'QUOTA',
    remarks: 'ESPORTS Prize pool + Water Reimbursement',
    reimbursement_notes: 'Reimbursed via GCash to Ate Daph',
    transacted_at: '2025-12-11T18:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Ate Daph',
    approvals: [],
    created_at: '2025-12-11T18:00:00Z',
  },
  {
    id: 'tx_fair_06',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_access',
    category_name: 'ACCESS Org Materials & Trophies',
    tracking_number: 'ACCSS-2025-EXP-006',
    title: 'Food for ACCESS Officers & Organizing Volunteers',
    description: 'Packed dinners for organizing officers (Lei, Andrey, Timmy, Charles, Tonio, Allan, Val).',
    type: 'REIMBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 700,
    wallet: 'GCASH',
    funding_source: 'ACCESS_GENERAL_FUNDS',
    remarks: 'CC Zuriel, Food for (Lei, Andrey, Timmy, Charles, Tonio, Allan, Val)',
    reimbursement_notes: 'Reimbursed 12.15.25',
    transacted_at: '2025-12-13T19:00:00Z',
    submitted_by_id: 'usr_treas_01',
    submitted_by_name: 'Food of ACCESS',
    approvals: [],
    created_at: '2025-12-13T19:00:00Z',
  },
  {
    id: 'tx_fair_07',
    event_budget_id: 'evt_cpe_fair_2025',
    event_name: 'CpE Fair Financial Summary',
    category_id: 'cat_fair_access',
    category_name: 'ACCESS Org Materials & Trophies',
    tracking_number: 'ACCSS-2025-EXP-007',
    title: 'Cartolina Materials for Photo Booth (2 pcs)',
    description: 'Black and orange cartolina paper for photo booth backdrop.',
    type: 'REIMBURSEMENT',
    status: 'TIER_2_PENDING',
    amount: 70,
    wallet: 'CASH_ON_HAND',
    funding_source: 'ACCESS_GENERAL_FUNDS',
    remarks: 'Cartolina 2pcs for Photo Booth',
    reimbursement_notes: 'not yet reimbursed (Cash on Hand)',
    transacted_at: '2025-12-13T14:00:00Z',
    submitted_by_id: 'usr_mem_01',
    submitted_by_name: 'Zuriel Valencia',
    approvals: [],
    created_at: '2025-12-13T14:00:00Z',
  },
  {
    id: 'tx_001',
    event_budget_id: 'evt_hardhatting_2026',
    event_name: 'Hardhatting Ceremony 2026',
    category_id: 'cat_hh_1',
    category_name: 'Hardhat Gear & Safety Collaterals',
    tracking_number: 'ACCSS-2026-EXP-001',
    title: 'Custom Engineering Hardhat Batch Procurement (120 pcs)',
    description: 'Bulk procurement of customized safety orange hardhats with department emblem stickers from SafetySupply Co.',
    type: 'DISBURSEMENT',
    status: 'CERTIFIED_DISBURSED',
    amount: 28400,
    transacted_at: '2026-06-28T10:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Ren Zapanta',
    receipt: {
      id: 'rcpt_001',
      transaction_id: 'tx_001',
      receipt_type: 'OFFICIAL_RECEIPT_SI',
      file_name: 'hardhat_invoice_bir_004921.webp',
      file_size: 142080,
      mime_type: 'image/webp',
      storage_path: 'receipts-vault/2026/hardhat_invoice_bir_004921.webp',
      sha256_hash: '9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b',
      ai_extracted_json: {
        vendor: 'SafetyFirst Industrial Supplies Inc.',
        or_number: 'SI-94821',
        date: '2026-06-28',
        line_items: [
          { name: 'Orange Hardhat Class E (Bulk)', quantity: 120, unit_price: 215, total: 25800 },
          { name: 'Custom Vinyl UV Logo Decals', quantity: 120, unit_price: 21.67, total: 2600 },
        ],
        computed_total: 28400,
        tax: 3042.85,
      },
      ai_confidence: 0.985,
    },
    approvals: [
      {
        id: 'appr_001_t1',
        transaction_id: 'tx_001',
        tier: 'TIER_1_PROJECT_HEAD',
        approver_id: 'usr_ph_01',
        approver_position: 'Hardhatting Committee Director',
        approver_incumbent_name: 'Ren Zapanta',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'Delivered and verified. 120 hardhats inspected in Room 424 CEA building.',
        signature_hash: '3f8e9a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f',
        signed_at: '2026-06-28T14:15:00Z',
      },
      {
        id: 'appr_001_t2',
        transaction_id: 'tx_001',
        tier: 'TIER_2_FINANCE_OFFICER',
        approver_id: 'usr_treas_01',
        approver_position: 'Finance Officer / Treasurer',
        approver_incumbent_name: 'Daniel Bithao',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'BIR Sales Invoice validated. Check paid to SafetyFirst account. Encrypted payment record archived.',
        signature_hash: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
        signed_at: '2026-06-29T09:30:00Z',
      },
      {
        id: 'appr_001_t3',
        transaction_id: 'tx_001',
        tier: 'TIER_3_PRESIDENT',
        approver_id: 'usr_pres_01',
        approver_position: 'Organization President',
        approver_incumbent_name: 'Sophia Lim',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'Certified and authorized. SHA-256 block #1 generated in ledger.',
        signature_hash: 'e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7',
        signed_at: '2026-06-29T11:00:00Z',
      },
    ],
    created_at: '2026-06-28T10:00:00Z',
  },
  {
    id: 'tx_002',
    event_budget_id: 'evt_hardhatting_2026',
    event_name: 'Hardhatting Ceremony 2026',
    category_id: 'cat_hh_3',
    category_name: 'Food & Dignitary Refreshments',
    tracking_number: 'ACCSS-2026-EXP-002',
    title: 'Catering & Packed Lunches for Faculty & Volunteers',
    description: 'Packed meals (Chicken Teriyaki + rice + drink) for 65 faculty members, guest alumni speakers, and student logistics staff.',
    type: 'REIMBURSEMENT',
    status: 'TIER_3_PENDING', // Awaiting President sign-off!
    amount: 14350,
    transacted_at: '2026-07-01T12:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Ren Zapanta',
    receipt: {
      id: 'rcpt_002',
      transaction_id: 'tx_002',
      receipt_type: 'OFFICIAL_RECEIPT_SI',
      file_name: 'catering_meals_or_58392.webp',
      file_size: 153200,
      mime_type: 'image/webp',
      storage_path: 'receipts-vault/2026/catering_meals_or_58392.webp',
      sha256_hash: '4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a',
      ai_extracted_json: {
        vendor: 'Catering Kitchen Sta. Mesa',
        or_number: 'OR-58392',
        date: '2026-07-01',
        line_items: [
          { name: 'Special Bento Meal Box with Drink', quantity: 65, unit_price: 220, total: 14300 },
          { name: 'Service & Packaging Fee', quantity: 1, unit_price: 50, total: 50 },
        ],
        computed_total: 14350,
      },
      ai_confidence: 0.991,
    },
    approvals: [
      {
        id: 'appr_002_t1',
        transaction_id: 'tx_002',
        tier: 'TIER_1_PROJECT_HEAD',
        approver_id: 'usr_ph_01',
        approver_position: 'Hardhatting Committee Director',
        approver_incumbent_name: 'Ren Zapanta',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'Meals distributed to all VIP faculty and volunteers on schedule.',
        signature_hash: '9f8e7d6c5b4a392817263544abcdef1234567890abcdef1234567890abcdef12',
        signed_at: '2026-07-01T15:30:00Z',
      },
      {
        id: 'appr_002_t2',
        transaction_id: 'tx_002',
        tier: 'TIER_2_FINANCE_OFFICER',
        approver_id: 'usr_treas_01',
        approver_position: 'Finance Officer / Treasurer',
        approver_incumbent_name: 'Daniel Bithao',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'Math verified. Category remaining balance is ₱3,650.00. Ready for President final sign-off.',
        signature_hash: '8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b',
        signed_at: '2026-07-02T10:00:00Z',
      },
    ],
    created_at: '2026-07-01T13:00:00Z',
  },
  {
    id: 'tx_003',
    event_budget_id: 'evt_ce_month_2026',
    event_name: 'Computer Engineering Month 2026',
    category_id: 'cat_ce_2',
    category_name: 'Prizes, Medals & Trophy Engraving',
    tracking_number: 'ACCSS-2026-EXP-003',
    title: 'Custom Laser-Engraved Acrylic Trophies & Medals',
    description: 'Overall champion departmental trophy and 1st/2nd/3rd place engraved medals for the hackathon and robotics competition.',
    type: 'REIMBURSEMENT',
    status: 'TIER_2_PENDING', // Awaiting Treasurer audit!
    amount: 18500,
    transacted_at: '2026-07-10T11:00:00Z',
    submitted_by_id: 'usr_ph_01',
    submitted_by_name: 'Charlean Broqueza',
    receipt: {
      id: 'rcpt_003',
      transaction_id: 'tx_003',
      receipt_type: 'OFFICIAL_RECEIPT_SI',
      file_name: 'trophies_receipt_7781.webp',
      file_size: 139400,
      mime_type: 'image/webp',
      storage_path: 'receipts-vault/2026/trophies_receipt_7781.webp',
      sha256_hash: '3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e',
      ai_extracted_json: {
        vendor: 'AcroPrint Awards & Trophies Quiapo',
        or_number: 'OR-7781',
        date: '2026-07-10',
        line_items: [
          { name: 'Custom Acrylic Perpetual Trophy 14-inch', quantity: 1, unit_price: 3500, total: 3500 },
          { name: 'Gold/Silver/Bronze Die-Cast Medals with Lanyard', quantity: 75, unit_price: 200, total: 15000 },
        ],
        computed_total: 18500,
      },
      ai_confidence: 0.978,
    },
    approvals: [
      {
        id: 'appr_003_t1',
        transaction_id: 'tx_003',
        tier: 'TIER_1_PROJECT_HEAD',
        approver_id: 'usr_ph_01',
        approver_position: 'CE Month Director',
        approver_incumbent_name: 'Charlean Broqueza',
        approver_term: 'A.Y. 2025-2026',
        action: 'APPROVED',
        comments: 'Trophies delivered in good condition with correct department lettering.',
        signature_hash: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
        signed_at: '2026-07-10T16:00:00Z',
      },
    ],
    created_at: '2026-07-10T12:00:00Z',
  },
  {
    id: 'tx_004',
    event_budget_id: 'evt_jao_seminar_2026',
    event_name: 'JAO Leadership & Technical Seminar Series',
    category_id: 'cat_jao_1',
    category_name: 'Workshop Materials & Handouts',
    tracking_number: 'ACCSS-2026-EXP-004',
    title: 'Training Kits, ID Lanyards & Presentation Handouts',
    description: 'Procurement of workshop folders, printed technical diagrams, and custom JAO lanyards for 45 trainee officers.',
    type: 'REIMBURSEMENT',
    status: 'TIER_1_PENDING', // Awaiting Project Head endorsement!
    amount: 5200,
    transacted_at: '2026-07-15T09:30:00Z',
    submitted_by_id: 'usr_mem_01',
    submitted_by_name: 'Lian Karyl Garcia',
    receipt: {
      id: 'rcpt_004',
      transaction_id: 'tx_004',
      receipt_type: 'OFFICIAL_RECEIPT_SI',
      file_name: 'supplies_or_28192.webp',
      file_size: 128500,
      mime_type: 'image/webp',
      storage_path: 'receipts-vault/2026/supplies_or_28192.webp',
      sha256_hash: '5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b',
      ai_extracted_json: {
        vendor: 'Pureza School & Office Supply',
        or_number: 'OR-28192',
        date: '2026-07-15',
        line_items: [
          { name: 'Clear Folders + Ring Clips (Pack of 50)', quantity: 1, unit_price: 1200, total: 1200 },
          { name: 'Colored Booklet Printing (45 sets)', quantity: 45, unit_price: 60, total: 2700 },
          { name: 'Sublimation Satin Lanyards (45 pcs)', quantity: 45, unit_price: 28.89, total: 1300 },
        ],
        computed_total: 5200,
      },
      ai_confidence: 0.982,
    },
    approvals: [],
    created_at: '2026-07-15T10:00:00Z',
  },
];

export const INITIAL_AUDIT_BLOCKS: AuditBlock[] = [
  {
    id: 'blk_000',
    transaction_id: 'genesis',
    tracking_number: 'GENESIS-BLOCK',
    block_index: 0,
    previous_hash: '0000000000000000000000000000000000000000000000000000000000000000',
    current_hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    title: 'PUP ACCESS Genesis Ledger Initialization',
    amount: 0,
    event_name: 'System Genesis (A.Y. 2025-2026)',
    certified_by_name: 'PUP ACCESS Executive Board',
    certified_by_position: 'President',
    timestamp: '2026-05-01T00:00:00Z',
  },
  {
    id: 'blk_001',
    transaction_id: 'tx_001',
    tracking_number: 'ACCSS-2026-EXP-001',
    block_index: 1,
    previous_hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    current_hash: 'e4d3c2b1a09876543210fedcba09876543210fedcba09876543210fedcba098',
    title: 'Custom Engineering Hardhat Batch Procurement (120 pcs)',
    amount: 28400,
    event_name: 'Hardhatting Ceremony 2026',
    certified_by_name: 'Sophia Lim',
    certified_by_position: 'Organization President',
    timestamp: '2026-06-29T11:00:00Z',
  },
];
